In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size
voc_size = 10000


In [6]:
## One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6073, 7343, 4813, 2696],
 [6073, 7343, 4813, 4280],
 [6073, 3402, 4813, 8218],
 [5101, 9598, 8258, 7771, 2246],
 [5101, 9598, 8258, 7771, 4248],
 [3144, 6073, 8951, 4813, 8976],
 [7633, 79, 7647, 7771]]

In [8]:
## word Embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [9]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6073 7343 4813 2696]
 [   0    0    0    0 6073 7343 4813 4280]
 [   0    0    0    0 6073 3402 4813 8218]
 [   0    0    0 5101 9598 8258 7771 2246]
 [   0    0    0 5101 9598 8258 7771 4248]
 [   0    0    0 3144 6073 8951 4813 8976]
 [   0    0    0    0 7633   79 7647 7771]]


In [13]:
## feature representation
dim = 10

In [14]:
## Create the model 
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 175ms/step


array([[[ 0.04532902,  0.01842714, -0.04881064,  0.04734954,
         -0.0458621 ,  0.02030471,  0.00319353,  0.01577506,
         -0.0447877 , -0.04770757],
        [ 0.04532902,  0.01842714, -0.04881064,  0.04734954,
         -0.0458621 ,  0.02030471,  0.00319353,  0.01577506,
         -0.0447877 , -0.04770757],
        [ 0.04532902,  0.01842714, -0.04881064,  0.04734954,
         -0.0458621 ,  0.02030471,  0.00319353,  0.01577506,
         -0.0447877 , -0.04770757],
        [ 0.04532902,  0.01842714, -0.04881064,  0.04734954,
         -0.0458621 ,  0.02030471,  0.00319353,  0.01577506,
         -0.0447877 , -0.04770757],
        [-0.01329043, -0.00362955,  0.03683859,  0.01121017,
         -0.01930497, -0.03912871, -0.03510883,  0.01172949,
          0.01027954,  0.02014253],
        [-0.00713259, -0.0444935 , -0.01860619, -0.02726451,
          0.03451293, -0.00883025,  0.00295211,  0.02637284,
          0.00775505,  0.0311552 ],
        [-0.02124838, -0.02452405, -0.0049702 ,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6073, 7343, 4813, 2696])

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 60ms/step


array([[ 0.04532902,  0.01842714, -0.04881064,  0.04734954, -0.0458621 ,
         0.02030471,  0.00319353,  0.01577506, -0.0447877 , -0.04770757],
       [ 0.04532902,  0.01842714, -0.04881064,  0.04734954, -0.0458621 ,
         0.02030471,  0.00319353,  0.01577506, -0.0447877 , -0.04770757],
       [ 0.04532902,  0.01842714, -0.04881064,  0.04734954, -0.0458621 ,
         0.02030471,  0.00319353,  0.01577506, -0.0447877 , -0.04770757],
       [ 0.04532902,  0.01842714, -0.04881064,  0.04734954, -0.0458621 ,
         0.02030471,  0.00319353,  0.01577506, -0.0447877 , -0.04770757],
       [-0.01329043, -0.00362955,  0.03683859,  0.01121017, -0.01930497,
        -0.03912871, -0.03510883,  0.01172949,  0.01027954,  0.02014253],
       [-0.00713259, -0.0444935 , -0.01860619, -0.02726451,  0.03451293,
        -0.00883025,  0.00295211,  0.02637284,  0.00775505,  0.0311552 ],
       [-0.02124838, -0.02452405, -0.0049702 ,  0.00692906,  0.01829575,
         0.04727731,  0.0163628 ,  0.0208169 